import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from 'react'
import CharacterList from '../components/index.js/characterList'
import Search from '../components/Search'

const Home = ({characters}:any) => {
  const [character,setcharacter] = useState(characters.results)
  console.log(character)

  // search functionality
  const onsearch = (value: string)=>{
    setcharacter(characters.results.filter((a:any) =>{
      return a.name.toLowerCase().startsWith(value.toLowerCase())
    }))
    console.log(value)
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      <h1>Ric and Morty</h1>
      <Search onsearch={onsearch}/>
      </header>
     <section className={styles.container}>
     <CharacterList character={character}/>
     </section>
      
    </div>
  )
}

export default Home

export async function getStaticProps() {
  const response = await fetch('https://rickandmortyapi.com/api/character')
  const data = await response.json()
  console.log(data)
 return{
  props: {
    characters: data
 },
}
}